# Generated by Django 4.1 on 2022-08-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_caption_post_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
