# Generated by Django 4.1 on 2022-08-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_profileimg_alter_profile_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profileimg',
        ),
    ]
