# Generated by Django 4.1 on 2022-08-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_likepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
